feature/#28 : 다운로드 모듈 패키지 구조 및 의존성 작업
The-Gleaners/streaming-system pull request #30
Opened 2023-05-01 10:05 UTC by brewagebear

다운로드 모듈 패키지 구조 및 의존성 추가 부분 PR입니다. 

구조는 현태님 PR을 참고하여 구성을 수행하였습니다.

```sh
.
├── build.gradle
└── src
    ├── main
    │   └── java
    │       └── gleaners
    │           ├── DownloaderApplication.java
    │           ├── domain
    │           │   └── Product.java
    │           ├── infrastructure
    │           │   └── kafka
    │           │       └── KafkaConfig.java
    │           ├── port
    │           │   ├── KafkaConsumer.java
    │           │   └── KafkaProducer.java
    │           └── usecase
    │               └── DownloadTask.java
    └── test
        └── java

```

추가된 의존성은 롬복 및 카프카, 테스트 도구 추가 

```groovy
description = "Data Download Module"

bootJar {
    enabled = false
}

jar {
    enabled = true
}

dependencies {
    implementation 'io.projectreactor.kafka:reactor-kafka'

    compileOnly 'org.projectlombok:lombok:1.18.20'
    annotationProcessor 'org.projectlombok:lombok:1.18.20'

    testImplementation 'io.projectreactor:reactor-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

test {
    useJUnitPlatform()
}
```

2023-05-01 12:05 UTC, Hyunta approved these changes
LGTM👍🏻

2023-05-01 12:07 UTC, brewagebear commented on downloader/src/test/java/gleaners/port/KafkaProducerTest.java
> +}
오 감사합니다 설정해두어야겠네요!

2023-05-01 13:47 UTC, lim-12 approved these changes
LGTM :grin:

2023-05-02 03:34 UTC, jongwoolim requested changes
확인해보면 좋을 것 같은 부분을 댓글로 달아두었습니다.
이 부분 확인 요청드리겠습니다!

2023-05-02 03:42 UTC, brewagebear commented on downloader/build.gradle
> +    implementation 'io.projectreactor.kafka:reactor-kafka'
매우 좋은 의견인 것 같습니다. 
@jwoo-o @kwan1989 @lim-12 @Hyunta @suhongkim98 

이거 `root` 모듈에 따로 빼서 `sub-project` 의존성에 추가해두도록하겠습니다. 
기존 머지된건 어쩔 수 없고, 나중에 main pull 받고, 문제없으면 의존성 지우는 식으로 작업하면 좋을거 같은데 어떻게 생각하실까요?

2023-05-02 03:45 UTC, brewagebear commented on downloader/build.gradle
> +    implementation 'io.projectreactor.kafka:reactor-kafka'
```groovy
subprojects {
    apply plugin: "java"
    apply plugin: "io.spring.dependency-management"
    apply plugin: "org.springframework.boot"

    dependencies {
        implementation("org.springframework.boot:spring-boot-starter")
        implementation("org.springframework.boot:spring-boot-starter-webflux")
        implementation("io.projectreactor.kafka:reactor-kafka")

        compileOnly("org.projectlombok:lombok:1.18.20")
        annotationProcessor("org.projectlombok:lombok:1.18.20")
        
        testImplementation("org.springframework.boot:spring-boot-starter-test")
    }
}
```

이런식으로 최상위 `build.gradle`에 추가될 것 같습니다.

2023-05-02 06:03 UTC, jongwoolim commented on downloader/build.gradle
> +    implementation 'io.projectreactor.kafka:reactor-kafka'
넵 좋은 것 같습니다!

2023-05-02 06:04 UTC, jongwoolim approved these changes

2023-05-02 06:07 UTC, brewagebear commented
@jongwoolim 님 수정하였는데 한번 확인해주실 수 있을까요?

2023-05-02 06:12 UTC, Hyunta approved these changes

2023-05-02 06:14 UTC, jongwoolim approved these changes

2023-05-02 08:43 UTC, lim-12 approved these changes

2023-05-02 08:51 UTC, merged