feature/#4 : 다운로드 인증 로직 추가
The-Gleaners/streaming-system pull request #37
Opened 2023-05-09 12:51 UTC by lim-12

인증을 위한 DownloadTarget record에 token 추가

2023-05-10 01:03 UTC, brewagebear requested changes
인증 값이 필요한 요청에 대한 기능을 구현하느라 고생이 많으셨습니다.
전반적으로 수정할 내용은 없으나 1가지 정도 제안을 드렸어서 이 부분 확인해보고 의논해보시는건 어떨까요?

이 부분 때문에 `request changes`로 두겠습니다.

2023-05-10 01:03 UTC, brewagebear commented on downloader/src/main/java/gleaners/domain/DownloadTarget.java
> -    String url
전달 드린 내용처럼 향후 AVRO 스키마 모듈쪽으로 넘어갈거같습니다.
해당 작업은 제가 수행하겠습니다.

2023-05-10 01:03 UTC, brewagebear commented on downloader/src/main/java/gleaners/usecase/Downloader.java
> +            return client.get()
이 부분은 인증 토큰이 존재할 경우 별도 메서드로 분리해서 리턴하는 건 어떨까요? 
```java
download() {
   if(hasTokenRequest()) {
      return tokenRequest();
   }
   return nomalRequest();
}
```
이런 방식이 좀 더 깔끔할 거 같습니다.

2023-05-10 01:03 UTC, brewagebear commented on downloader/src/test/java/gleaners/usecase/DownloaderTest.java
> +        DownloadTarget downloadTarget = new DownloadTarget("http://httpstat.us/200", null);
인증이 필요한 요청에 대한 테스트 코드는 `trigger` 모듈쪽에서 작업해두도록 하겠습니다.

2023-05-11 11:44 UTC, brewagebear approved these changes
LGTM 👍

2023-05-15 02:53 UTC, kwan1989 approved these changes

2023-05-15 03:11 UTC, merged