feature/#12-로더-카프카-컨슈머-개발 :
The-Gleaners/streaming-system pull request #41
Opened 2023-05-11 08:47 UTC by kwan1989

1. 로더 카프카, 몽고 작성

2023-05-11 11:51 UTC, brewagebear requested changes
로더쪽 카프카 컨슈머 개발을 하느라 고생이 많으셨습니다. 

몇가지 코멘트를 남겨드렸는데 이 부분 의논해봤으면 해서, `Request Changes`로 두겠습니다.

2023-05-11 11:51 UTC, brewagebear commented on build.gradle
>      dependencies {
<img width="919" alt="Screenshot 2023-05-11 at 20 47 55" src="https://github.com/The-Gleaners/streaming-system/assets/22961251/0a5c1f18-9e29-4f9a-8f6a-98c79d7d49fa">

브랜치 명에 한글이 포함되서 경고가 발생하는 것 같습니다. 추후에 브랜치명 수정 요청드리도록 하겠습니다. 
e.g) feature/#12

2023-05-11 11:51 UTC, brewagebear commented on loader/src/main/java/gleaners/loader/port/ReactiveKafkaConsumer.java
> +//                .doOnNext(this::saveToMongo)
해당 부분의 주석의 의도가 궁금합니다!

2023-05-11 12:41 UTC, lim-12 commented
브레이스가 전체적으로 섞여있는 거 같습니다.
코드 컨벤션에 맞게 전체적으로 수정 요청드립니다 !

public void method() {
.... ( 내용 ) ....
}

2023-05-11 12:43 UTC, lim-12 commented on loader/src/main/java/gleaners/loader/port/ReactiveKafkaConsumer.java
> +      return  loaderTargetRepository.save(message.value())
여기 return과 loaderTargetRepository 사이 띄어쓰기 2칸인 거 같습니다.

2023-05-11 12:48 UTC, brewagebear commented
> 브레이스가 전체적으로 섞여있는 거 같습니다. 코드 컨벤션에 맞게 전체적으로 수정 요청드립니다 !
> 
> public void method() { .... ( 내용 ) .... }

이 부분 제가 xml 최근꺼로 업데이트 안한거 같아서 위키에 최신화해두도록 하겠습니다.

2023-05-11 13:00 UTC, lim-12 commented on loader/src/main/java/gleaners/loader/port/ReactiveKafkaConsumer.java
> +                .doOnNext(message -> saveToMongo(message).subscribe())
doOnNext(processReceiveMessage()) 메서드 내부에서 offset 을 커밋하고 있는데 saveToMongo 시도 중 에러가 발생하면 어떻게 되는건가요 ?

2023-05-15 01:33 UTC, kwan1989 commented on build.gradle
>      dependencies {
1. Old - [feature/#12-로더-카프카-컨슈머-개발] 
2. New - [feature/#12]

변경하도록 하겠습니다. 🫶🏻

2023-05-15 01:35 UTC, kwan1989 commented on loader/src/main/java/gleaners/loader/port/ReactiveKafkaConsumer.java
> +//                .doOnNext(this::saveToMongo)
메서드내에서 람다로 처리하기위해 작성하였다가, 원복 후 정리하지 못했습니다.
확인 감사드립니다.

2023-05-15 05:38 UTC, kwan1989 commented on loader/src/main/java/gleaners/loader/port/ReactiveKafkaConsumer.java
> +                .doOnNext(message -> saveToMongo(message).subscribe())
해당 내용으로 컨슈머/저장 의 롤을 따로 잡아놨기에 
1. 데이터 컨슈머
2. 저장
을 기존에 따로 처리 했더라면 한 사이클로 묶어야할 것 같아 수정 진행 하겠습니다.

의견 감사합니다.

2023-05-15 05:44 UTC, closed without merging