Feature/#43 : 로컬 작업을 원할하게 하기 위한 gradle docker-compose task 작업 추가
The-Gleaners/streaming-system pull request #44
Opened 2023-05-16 06:11 UTC by brewagebear

1. InfraStructure 레포를 다운로드 받는 태스크 추가 
2. 해당 레포를 기준으로 docker-compose를 통해서 로컬 환경 구성하는 태스크 추가

2023-05-16 06:50 UTC, lim-12 commented on trigger/build.gradle.kts
> +
trigger 쪽은 build.gradle이 kts 인 이유가 있나요 ?

2023-05-16 06:57 UTC, lim-12 commented on build.gradle
> +    infraGithubCloneTargetDir = "$rootDir/.local-infra"
$rootDir 값은 어디서 불러오는건가요 ?

2023-05-16 08:56 UTC, brewagebear commented on build.gradle
> +    infraGithubCloneTargetDir = "$rootDir/.local-infra"
`$rootDir`은 프로젝트 루트 경로라고 보시면될거같습니다. 그래들 환경변수입니다.

2023-05-16 08:57 UTC, brewagebear commented on trigger/build.gradle.kts
> +
향후 나머지 모듈도 코틀린으로 변경하려는데 아직 선행작업들이 많아서 트리거만 미리 작업해두었습니다.

2023-05-18 03:36 UTC, Hyunta requested changes
gradle 파일 작성하시느라 고생하셨습니다!
현재 commit 내역이 조금 꼬여있는 것 같은데 해결한 뒤에 Merge해야할 것 같습니다.

2023-05-18 03:36 UTC, Hyunta commented on proccessor/src/main/java/domain/Ep.java
> +package domain;
processor 쪽 제가 올린 PR들이 같이 반영되어 있는 것 같네요
저번에 main rollback하면서 그런 것 같은데 해당 PR Merge하면서 누락된 내용 반영해도 괜찮을 것 같습니다.

2023-05-18 03:36 UTC, Hyunta commented on downloader/src/main/java/gleaners/domain/DownloadTarget.java
>  package gleaners.domain;
아 근데 현교님 commit 내역도 같이 반영되고 있는 것 같아서 cherry pick으로 새로 파시거나 현교님 코드 merge 되고 나면 다시 rebase 받아서 진행하는게 나을 것 같습니다

2023-05-18 07:41 UTC, brewagebear commented on downloader/src/main/java/gleaners/domain/DownloadTarget.java
>  package gleaners.domain;
넵 이 부분 리베이스 해서 처리하도록 하겠습니다.

2023-05-18 07:50 UTC, brewagebear commented on proccessor/src/main/java/domain/Ep.java
> +package domain;
어 이 부분 어떤 내용인지 알 수 있을까요?

2023-05-18 08:59 UTC, lim-12 commented on proccessor/src/main/java/domain/Ep.java
> +public class Ep {
Ep 도메인은 용도가 어떻게 되는건가요 ?

2023-05-18 08:59 UTC, 7makers commented on proccessor/src/main/java/domain/Ep.java
> +public class Ep {
불 필요한 파일인데 추가된거 같습니다 삭제 진행하겠습니다.

2023-05-18 09:03 UTC, brewagebear commented on proccessor/src/main/java/domain/Ep.java
> +public class Ep {
@lim-12 님 이 부분은 확인해보니 `Processor`쪽 작업 분이 반영된 부분이 있어서 리베이스 했을 때 딸려온 것으로 보이네요. 
아마 프로세서쪽 패키지 베이스 작업할때 남겨진 부분으로 보입니다.

2023-05-18 09:22 UTC, lim-12 approved these changes

2023-05-18 13:33 UTC, Hyunta approved these changes

2023-05-18 14:39 UTC, merged

2023-05-25 12:41 UTC, brewagebear commented on proccessor/src/main/java/domain/Ep.java
> +package domain;
아 늦게 봤네요 이 부분 디스코드에서 얘기나누시는거 어떨까요?