feature/#5 : 파일 사이즈를 이용한 수집 진행 여부 확인 로직 추가
The-Gleaners/streaming-system pull request #47
Opened 2023-05-18 02:13 UTC by lim-12

Trigger에서 보내준 파일 사이즈 ( 이전 수집 파일 사이즈 ) 와 header 의 content-length를 비교하여 수집 여부를 결정한다.
해당 로직은 전체 EP 상에서만 실행되어야하는 로직인데 아직 전체/요약에 대한 타입을 나누지 않아서 무조건 사이즈 비교하는 방식으로 구현되어있다.

2023-05-18 03:23 UTC, Hyunta requested changes
검증하는 기능 구현하느라 고생하셨습니다!
편하게 읽히고 코드양이 적당해서 리뷰하기 편했습니다ㅎㅎ
관련해서 제가 잘 모르는 부분들이 있어서 커멘트로 남겨놨습니다 확인부탁해요🙏🏻

2023-05-18 03:23 UTC, Hyunta commented on downloader/src/main/java/gleaners/usecase/Downloader.java
> +    private Mono<String> validate(
response에 대한 validation이 이뤄지는 것 같은데 메서드 이름을 조금 더 구체적으로 써주면 좋을 것 같습니다!

---
메서드는 마치 검증만 하고 있는 것처럼 보이지만 기능이 조금 많이 있는 것 같습니다.
1. response가 error 인지 검증
2. downloadTarget이 적정한 수량을 갖고 있는지
3. 정상 응답일 경우 Mono로 변환

1,2 번 기능은 같이 있어도 괜찮을 것 같은데 메서드를 조금 나눠두면 어떨까요?
```java
validateResult(
        ClientResponse response,
        DownloadTarget requestTarget){
validateResponse(response)
validateDownloadTarget(requestTarget)
}
```
제가 Spring Webflux를 잘 안써봐서 혹시 따로 구현하는게 가능하다면 3번은 분리하는게 어떨까요?

2023-05-18 03:23 UTC, Hyunta commented on downloader/src/main/java/gleaners/usecase/Downloader.java
> +        long fileSize = response.headers().contentLength().orElse(-1L);
-1L도 상수로 묶어서 표현해줄 수 있을 것 같아요
`private static final long NO_CONTENT_LENGTH = 1L`

2023-05-18 03:23 UTC, Hyunta commented on downloader/src/main/java/gleaners/usecase/Downloader.java
> +    private boolean isDownload(long fileSize, DownloadTarget requestTarget) {
isDownload -> canDownload 로 변경하는 건 어떨까요?
다운로드가 가능한지 확인하는 메서드처럼 보여서요

2023-05-18 03:23 UTC, Hyunta commented on downloader/src/main/java/gleaners/usecase/Downloader.java
> +        long allowanceSize = requestTarget.fileSize() / 100 * requestTarget.allowance();
제가 잘 몰라서 이 로직에 대해서 조금 설명해주실 수 있을까요?

2023-05-18 03:23 UTC, Hyunta commented on downloader/src/main/java/gleaners/domain/DownloadTarget.java
> +    int allowance
fileSize는 long인데 allowance는 int로 설정해주신 이유를 알 수 있을까요?

2023-05-18 04:20 UTC, lim-12 commented on downloader/src/main/java/gleaners/domain/DownloadTarget.java
> +    int allowance
allowance는 백분율 값을 넣는 필드이기 때문에 범위가 0~100이라서 int 형으로 지정하였습니다.
추후에 소수점 단위까지 확장하여 체크해야되는 니즈가 있다면 float나 double로 처리하면 될 거 같습니다.

2023-05-18 04:25 UTC, lim-12 commented on downloader/src/main/java/gleaners/usecase/Downloader.java
> +        long allowanceSize = requestTarget.fileSize() / 100 * requestTarget.allowance();
requestTarget.fileSize() : 이전 수집 때 다운로드 받은 file 사이즈
requestTarget.allowance() : 수집 가능 허용치
allowanceSize는 HttpClient 로 요청한 파일을 다운로드를 진행하기 위한 파일의 최소 사이즈라고 보시면 될 거 같습니다.

예를 들어 허용치를 70(%) 로 설정해놨다고 가정하고 설명드리겠습니다.
이전 수집 때 파일 사이즈가 1000byte 였다면 허용치가 70(%)으로 설정되어있을 때는 1000byte 의 70% 이상의 사이즈가 들어와야 수집을 허용한다는 의미입니다.

1000byte / 100 * 70(%) = 700byte
결과가 700byte가 나오므로 700byte보다 content-length가 작아질 경우 수집을 진행하지 않는 로직입니다.

2023-05-18 04:25 UTC, lim-12 commented on downloader/src/main/java/gleaners/usecase/Downloader.java
> +    private boolean isDownload(long fileSize, DownloadTarget requestTarget) {
좋은 거 같습니다 ! 수정하도록 하겠습니다.

2023-05-18 04:27 UTC, lim-12 commented on downloader/src/main/java/gleaners/usecase/Downloader.java
> +    private Mono<String> validate(
이 부분 저도 확인해본 후에 수정 가능하다면 수정하도록 하겠습니다.

2023-05-18 04:27 UTC, lim-12 commented on downloader/src/main/java/gleaners/usecase/Downloader.java
> +        long fileSize = response.headers().contentLength().orElse(-1L);
수정하도록 하겠습니다 !

2023-05-18 05:14 UTC, lim-12 commented on downloader/src/main/java/gleaners/usecase/Downloader.java
> +    private Mono<String> validate(
이 부분 일단은 isValid 메서드 내부에서 다운로드 유효성 검사를 먼저한 후에 body mono를 보낼 지 empty mono를 보낼지 결정하게 수정해놨습니다. 
체크할 validation 들이 계속 늘어나다보면 만들면 Downloader 쪽이 너무 커질 거 같다고 생각했고 현재 작업 중인 컨버터 쪽에서 유효성 검사도 진행 중인데 validation 관련해서 인터페이스로 묶어서 처리할 수 있도록 수정해두겠습니다.

2023-05-18 05:50 UTC, brewagebear requested changes
파일 사이즈 판별 유무 리서치부터 해당 로직 구현하느라 고생 많으셨습니다 👍 

이야기 나누면 좋을 부분들은 코멘트 남겨드렸는데 이 부분 같이 확인하면 좋을 것 같아서 `Request Changes` 걸어두고, 댓글을 남겨드려봅니다.

2023-05-18 05:50 UTC, brewagebear commented on downloader/src/main/java/gleaners/usecase/Downloader.java
> +        long allowanceSize = requestTarget.fileSize() / 100 * requestTarget.allowance();
그렇다면, 메서드 명을 바꾸는건 어떨까요? 

허용치를 `allowance`로 표현하신거 같아서 

`isSmallerAllowance()` 이라는 메서드라는 이름과 비슷한 메서드 명을 제안드려봅니다.

2023-05-18 05:50 UTC, brewagebear commented on downloader/src/main/java/gleaners/usecase/Downloader.java
> +                if(isValid(r, requestTarget)) return r.bodyToMono(String.class);
`r`이 보았을 때 정확히 어떤건지 와닿지 않다고 느끼는데 어떻게 생각하실까요? 

따라서, `r`보다 WebClient의 `response`로 보이는데 `response`를 명시하는게 좋아보입니다. 

그리고, 람다 내부의 if ~ else 부분도 별도의 메서드로 변환하는게 좋아보이는데 이는 어떻게 생각하실까요?

2023-05-18 07:07 UTC, Hyunta requested changes
빠른 피드백 감사합니다!
허용치 관련해서 한번 확인 부탁드립니다.

2023-05-18 07:07 UTC, Hyunta commented on downloader/src/main/java/gleaners/usecase/Downloader.java
> +        long allowanceSize = requestTarget.fileSize() / 100 * requestTarget.allowance();
`requestTarget` 이름을 `downloadTarget`으로 클래스 이름과 동일하게 유지하는 것도 좋을 것 같습니다

2023-05-18 07:07 UTC, Hyunta commented on downloader/src/main/java/gleaners/domain/DownloadTarget.java
> +    int allowance
`allowance` 라는 표현을 조금 구체적으로 `minDownloadAllowanceRate` 혹은 `minAllowanceRate` 라고 작성해두면 변수가 비율인지와 어떤 기준인지 파악하기 쉬울 것 같습니다.

2023-05-18 07:07 UTC, Hyunta commented on downloader/src/main/java/gleaners/domain/DownloadTarget.java
> +    int allowance
추가로 fileSize는 그럼 이전에 다운받은 파일의 사이즈라고 보여지는데 맞을까요?
맞다면 이름을 `prevFileSize` 로 변경하는게 나아보입니다ㅎㅎ

2023-05-22 05:14 UTC, brewagebear approved these changes
아브로 스키마 부분만 반영하면 끝날 거 같습니다.
금방 수정될 거 같아서 `Approve` 하겠습니다.

고생 많으셨습니다.

2023-05-22 05:14 UTC, brewagebear commented on downloader/src/main/java/gleaners/domain/DownloadTarget.java
>  public record DownloadTarget(
번거로우시겠지만, 아브로 쪽이 선행 머지가 되서 이 부분 한번 아브로 스키마로 수정 요청 드릴 수 있을까요?
죄송합니다. ㅠㅠ

2023-05-22 05:31 UTC, Hyunta approved these changes

2023-05-22 05:43 UTC, lim-12 commented on downloader/src/main/java/gleaners/domain/DownloadTarget.java
>  public record DownloadTarget(
네네. 머지 전에 리베이스하려고 했는데 .. 리베이스해서 코드 최신화 먼저 진행하겠습니다.

2023-05-23 00:38 UTC, merged